
# Stage 1: base images
FROM node:lts-alpine as base

RUN mkdir -p /home/node/app && chown -R node:node /home/node/app

WORKDIR /home/node/app

# setup pnpm
RUN npm install -g pnpm@6.15.1 nodemon

USER node

CMD pnpm config set store-dir /home/node/.pnpm-store \
    && pnpm i --shamefully-hoist \
    && npm start
